### ISSUE TITLE
Is there any way to get the actual .exe name?

### ISSUE THREAD

**Issue by Rikihanks** [osztenkurden/steam-game-path#3]
Currently this good library returns the game path, but what if we need to get also the .exe name (which is not included in the path)?
For example, the among us instalation has 2 .exe files in it, would be any way to get the actual game .exe? Is that info available through this method?

**Comment by osztenkurden** [comment]
Hi! While I can look into it, Im fairly sure I wont be able to access that information, as I didnt see it anywhere. Ill research this this week

**Comment by Nocccer** [comment]
just a simple `where steam` maybe ?

**Comment by osztenkurden** [comment]
@Rikihanks npm has already 2.2.0, getGamePath(appId, true) gets you object which has promise on .game.executable which will resolve to an array of executables
